export * from "./arrays";
export * from "./bool";
export * from "./dates";
export * from "./funcion";
export * from "./generic";
export * from "./numbers";
export * from "./objects";
export * from "./strings";
export * from "./undefined";
